version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ~/container_data/gitea:/data
    ports:
      - "3000:3000"
      #- "222:22"
