gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: '192.168.99.1'
  #environment:
    #GITLAB_OMNIBUS_CONFIG: |
      #external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '~/container_data/gitlab/config:/etc/gitlab'
    - '~/container_data/gitlab/logs:/var/log/gitlab'
    - '~/container_data/gitlab/data:/var/opt/gitlab'
